config/routes.rb
Rails.application.routes.draw do

  get 'devices/register'
  resources :devices

  get 'outputs/notify'

  get 'outputs/accept'
  get 'outputs/io_sample'

  resources :outputs

  get 'panels/remote_command' 
  resources :panels

  root 'panels#index'

end

app/models/output.rb
class Output < ActiveRecord::Base
  belongs_to :panel

  validates :watt, :presence => true

   after_save :notify_change

  def notify_change
    Output.connection.execute "NOTIFY outputs, '#{ self.id}'"
  end

  def self.on_change
    Output.connection.execute 'LISTEN outputs'
    loop do
      puts "inside loop"
      Output.connection.raw_connection.wait_for_notify do |event, pid, outputs|
        yield outputs
      end
    end

  ensure
    connection.execute 'UNLISTEN outputs'
  end


end

app/controllers/outputs_controller.rb
class OutputsController < ApplicationController
  include ActionController::Live


  before_action :set_output, only: [:show, :edit, :update, :destroy]

  before_action :set_device, only: [:io_sample]
  # GET /outputs
  # GET /outputs.json
  def index
    @outputs = Output.all.order(:created_at)
  end 
  
  # GET /outputs/notify
  def notify
      # SSE expects the `text/event-stream` content type
      response.headers['Content-Type'] = 'text/event-stream'

      sse = Reloader::SSE.new(response.stream)

      begin
        # Watch the output change
        Output.on_change do |id|
          output =  Output.find(id)
          # Send a message on the "refresh" channel on every update
          sse.write({:panel=>output.panel_id, :watt => output.watt} , :event => 'update_output')
        end

      rescue IOError
        # When the client disconnects, we'll get an IOError on write
      ensure
        sse.close
      end

      render nothing: true
  end

  # GET /outoputs/accept
  def accept

    output = Output.new(accept_output)
    if output.save
    else
    end

    render nothing: true
  end

  def io_sample
    puts @device.panels.count
    @device.panels.each do |panel|
    	puts "panel:#{panel.source} =>#{params[panel.source]}"
	output = Output.new
	
	output.panel_id = panel.id
	output.watt = params[panel.source]
	output.watt *= panel.max
	if output.save
	else
	end
    end
    
    render nothing: true

  end

  # GET /outputs/1
  # GET /outputs/1.json
  def show
  end

  # GET /outputs/new
  def new
    @output = Output.new
  end

  # GET /outputs/1/edit
  def edit
  end

  # POST /outputs
  # POST /outputs.json
  def create
    @output = Output.new(output_params)

    respond_to do |format|
      if @output.save
        format.html { redirect_to @output, notice: 'Output was successfully created.' }
        format.json { render :show, status: :created, location: @output }
      else
        format.html { render :new }
        format.json { render json: @output.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /outputs/1
  # PATCH/PUT /outputs/1.json
  def update
    respond_to do |format|
      if @output.update(output_params)
        format.html { redirect_to @output, notice: 'Output was successfully updated.' }
        format.json { render :show, status: :ok, location: @output }
      else
        format.html { render :edit }
        format.json { render json: @output.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outputs/1
  # DELETE /outputs/1.json
  def destroy
    @output.destroy
    respond_to do |format|
      format.html { redirect_to outputs_url, notice: 'Output was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_output
      @output = Output.find(params[:id])
    end

    def	set_device
      @device = Device.find_by_device_id(params[:device_id])
    end

  def accept_output
    params.permit(:watt, :voltage)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
    def output_params
      params.require(:output).permit(:watt, :voltage)
    end
end

app/helpers/outputs_helper.rb
module OutputsHelper
end

app/views/outputs/_form.html.erb
<%= form_for @output, :html => { :class => "form-horizontal output" } do |f| %>

    <% if @output.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@output.errors.count, "error") %> prohibited this output from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @output.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :watt, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :watt, :class => 'form-control' %>
    </div>
    <%= error_span(@output[:watt]) %>
  </div>
  <div class="control-group">
    <%= f.label :voltage, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :voltage, :class => 'form-control' %>
    </div>
    <%= error_span(@output[:voltage]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            outputs_path, :class => 'btn btn-default' %>

<% end %>

app/views/outputs/edit.html.erb
<%- model_class = Output -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/outputs/index.html.erb
<%- model_class = Output -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:watt) %></th>
      <th><%= model_class.human_attribute_name(:voltage) %></th>
      <th><%= model_class.human_attribute_name(:date) %></th>
        <th><%= model_class.human_attribute_name(:time) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @outputs.each do |output| %>
      <tr>
        <td><%= link_to output.id, output_path(output) %></td>
        <td><%= output.watt %></td>
        <td><%= output.voltage %></td>
        <td><%= output.created_at.to_time %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_output_path(output), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      output_path(output),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_output_path,
            :class => 'btn btn-primary' %>

app/views/outputs/new.html.erb
<%- model_class = Output -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/outputs/notify.html.erb
<h1>Outputs#notify</h1>
<p>Find me in app/views/outputs/notify.html.erb</p>

app/views/outputs/show.html.erb
<%- model_class = Output -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:watt) %>:</strong></dt>
  <dd><%= @output.watt %></dd>
  <dt><strong><%= model_class.human_attribute_name(:voltage) %>:</strong></dt>
  <dd><%= @output.voltage %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              outputs_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_output_path(@output), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              output_path(@output),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>